apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
  labels:
    chapter: jobs
spec:
  template:
    metadata:
      labels:
        chapter: jobs
    spec:
      containers:
      - name: curl
        image: alpine/curl:3.14
        imagePullPolicy: Always
        command: #TODO
      restartPolicy: OnFailure
